runtime: python37

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

entrypoint: gunicorn --chdir back-end -b :8080 wsgi:app

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /static
  static_dir: front-end/build/static/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto